수업 9, 10/03-django-urls/articles/urls.py
from django.urls import path
# 명시적 상대경로
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('dinner/', views.dinner, name='dinner'),
    path('search/', views.search, name='search'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    # path('hello/<str:name>/', views.greeting),
    path('hello/<name>/', views.greeting, name='greeting'),
    path('articles/<int:num>/', views.detail, name='detail'),
]

수업 9, 10/03-django-urls/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

수업 9, 10/03-django-urls/pages/urls.py
from django.urls import path
# 명시적 상대경로
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
]

수업 9, 10/03-django-urls/articles/models.py
from django.db import models

# Create your models here.

수업 9, 10/03-django-urls/pages/models.py
from django.db import models

# Create your models here.

수업 9, 10/03-django-urls/articles/views.py
import random
from django.shortcuts import render


# Create your views here.
def index(request):
    context = {
        'name': 'Jane',
    }
    return render(request, 'articles/index.html', context)


def dinner(request):
    foods = ['국밥', '국수', '카레', '탕수육',]
    picked = random.choice(foods)
    empty_list = []
    context = {
        'foods': foods,
        'picked': picked,
        'empty_list': empty_list,
    }
    return render(request, 'articles/dinner.html', context)


def search(request):
    return render(request, 'articles/search.html')


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    # 사용자로 부터 요청을 받아서
    # 요청에서 사용자 입력 데이터를 찾아
    # context에 저장 후 catch 템플릿에 출력
    # print(request)
    # print(type(request))
    # print(request.GET)
    # print(request.META)
    # print(request.GET.get('message'))
    message = request.GET.get('message')
    context = {
        'message': message,
    }
    return render(request, 'articles/catch.html', context)


def greeting(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/greeting.html', context)


def detail(request, num):
    context = {
        'num': num,
    }
    return render(request, 'articles/detail.html', context)

수업 9, 10/03-django-urls/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

수업 9, 10/03-django-urls/articles/templates/articles/catch.html
{% extends "base.html" %}

{% block content %}
  <h1>Throw로 부터 {{ message }}를 받아따!!!!</h1>
{% endblock content %}

수업 9, 10/03-django-urls/articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>여기는 {{ num }}번 게시글 페이지입니다.</h1>
{% endblock content %}

수업 9, 10/03-django-urls/articles/templates/articles/dinner.html
{% extends "base.html" %}

{% block content %}
  <p>{{ picked }} 메뉴가 선택되었습니다.</p>
  <p>{{ picked|length }} 글자입니다.</p>
  <h2>메뉴판</h2>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>

  {% if empty_list|length == 0 %}
    <p>메뉴가 소진 되었습니다.</p>
  {% else %}
    <p>아직 메뉴가 남았습니다.</p>
  {% endif %}
{% endblock content %}

수업 9, 10/03-django-urls/articles/templates/articles/greeting.html
{% extends "base.html" %}

{% block content %}
  <h1>안녕, {{ name }}</h1>
{% endblock content %}

수업 9, 10/03-django-urls/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
  <h1>안녕, {{ name }}</h1>
  <a href="{% url "articles:dinner" %}">dinner</a>
  <a href="{% url "articles:search" %}">search</a>
  <a href="{% url "articles:throw" %}">throw</a>
  <a href="{% url "pages:index" %}">두번째 앱의 메인 페이지</a>
{% endblock content %}

수업 9, 10/03-django-urls/articles/templates/articles/search.html
{% extends "base.html" %}

{% block content %}
  <h1>fake naver</h1>
  <form action="https://search.naver.com/search.naver/" method="GET">
    <label for="message">검색어:</label>
    <input type="text" name="query" id="message">
    <input type="submit">
  </form>
{% endblock content %}

수업 9, 10/03-django-urls/articles/templates/articles/throw.html
{% extends "base.html" %}

{% block content %}
  <h1>Throw</h1>
  <form action="{% url "articles:catch" %}" method="GET">
    <label for="message">메세지:</label>
    <input type="text" name="message" id="message">
    <input type="submit">
  </form>
{% endblock content %}

수업 9, 10/03-django-urls/pages/templates/pages/index.html
{% extends "base.html" %}

{% block content %}
  <h1>두번째 앱 pages의 메인 페이지</h1>
{% endblock content %}

수업 9, 10/03-django-urls/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>